# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Research
email: brvillas@ucsc.edu
description: > # this means to ignore newlines until "baseurl:"
  A simple blog to document my research
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://bvillasen.github.io/blog" # the base hostname & protocol for your site
twitter_username:
github_username:  bvillasen


# theme: jekyll-theme-dinky

# Build settings
# markdown: redcarpet
markdown: kramdown

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
